const mongoose = require("mongoose");
const db = require("../models");

//need file to empty the Charity collection and insert charities below??

mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/Charity"
  );

const charitySeed =[
    {
        name: "Edna House",
        thumbnail: "https://www.guidestar.org/ViewEdoc.aspx?eDocId=6169876&approved=True",
        href: "www.ednahouse.org",
        address: "2007 West 65th Street",
        city: "Cleveland",
        state: "Ohio",
        zipCode: 44102,
        phone: "216-281-7751",
        EIN: "14-1912872",
        mainCause:"Sober living for women",
        causes: [
            "women",
            "recovery",
            "drug abuse",
            "substance abuse",
            "addiction",
            "drug addiction",
            "alcoholism",
            "alcohol abuse",
            "sobriety",
            "sober living",
            "sober housing"
        ],
        mission: "The Edna House for Women is dedicated to providing means and opportunity to women affected by alcohol and drug addiction so that they may achieve sobriety by developing mentally, spiritually and emotionally through a blend of 12-step recovery, life, and career services.",
        contactEmail: "mail@ednahouse.org",
        acceptedItems: [
            "Big Books", 
            "cleaning products", 
            "Murphy's Oil Soap", 
            "household cleaner", 
            "cleaner",
            "floor cleaner",
            "bathroom cleaner",
            "cleaning supplies",
            "bleach",
            "sponges",
            "spray bottles",
            "mops",
            "garbage bags",
            "canned food",
            "condiments",
            "snacks",
            "non-perishable snacks",
            "coffee",
            "creamer",
            "sugar",
            "paper towels",
            "toilet paper",
            "tampons",
            "gift cards",
            "bus passes",
            "postage stamps",
            "flash drives",
            "paper",
            "copier paper",
            "printer paper",
            "resume paper",
            "women's clothing",
            "women's shoes",
            "food",
            "toiletries"
        ],
        donationMethod: "Donations may be dropped off at The Edna House seven days a week during daylight hours."
    },
    {
        name: "Dress for Success Cleveland",
        thumbnail: "https://cleveland.dressforsuccess.org/wp-content/uploads/2014/12/DFS_Cleveland-Web.jpg",
        href: "https://cleveland.dressforsuccess.org/",
        address: "2239 East 55th Street",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44103",
        phone: "216-391-2301",
        EIN: "34-1872331",
        mainCause:"Economic independence for women",
        causes: [
            "women",
            "poverty",
            "professional development",
            "economic",
            "economic independence",
            "financial",
            "career",
            "network",
            "networking",
            "support",
            "professional support",
            "work",
            "jobs"
            ],
        mission: "The mission of Dress for Success Cleveland is to promote the economic independence of disadvantaged women by providing professional attire, a network of support and the career development tools to help women thrive in work and life.",
        contactEmail: "DFSC@dressforsuccesscleveland.org",
        acceptedItems: [
            "bus passes",
            "buss pass",
            "gas cards",
            "gift cards",
            "phone cards",
            "grocery gift cards",
            "toiletries",
            "jewelry",
            "women's jewelry",
            "women's coats",
            "women's jackets",
            "coats",
            "jackets",
            "coat",
            "jacket",
            "winter coats",
            "winter coat",
            "winter jacket",
            "winter jackets"
        ],
        donationMethod: "Items may be mailed or dropped off by appointment. Schedule an appointment."
    },
    {
        name: "Domestic Violence & Child Advocacy Center",
        thumbnail: "https://dvcac.org/wp-content/uploads/2017/10/2015-New-Logo-Large-Transparent-2-e1513881586605.png",
        href: "https://dvcac.org/",
        address: "P.O. Box 5466",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44101",
        phone: "216-229-2420",
        EIN: "34-1278377",
        mainCause:"Domestic Violence, Child Abuse",
        causes: [
            "child abuse",
            "human services",
            "domestic violence",
            "shelter",
            "domestic violence shelters",
            "mental health",
            "mental health care",
            "domestic abuse",
            "rape",
            "children",
            "youth",
            "women",
            "girls",
            "child",
            "victim",
            "victims",
            "victims of crime",
            "victims of abuse",
            "abuse",
            "crisis intervention"
        ],
        mission: "Our mission is to provide services that foster safety and healing for those affected by child abuse and domestic violence; and to prevent abuse through education, advocacy, and systemic change.",
        contactEmail: "lreddick @dvcac.org",
        acceptedItems: [
            "gift cards",
            "Target gift cards",
            "Walmart gift cards",
            "Home Depot gift cards",
            "Giant Eagle gift cards",
            "Costco Gift Cards",
            "Visa Gift Cards",
            "body lotion",
            "lotion",
            "deodorant",
            "hand soap dispensers",
            "hand soap",
            "soap",
            "body soap",
            "body wash", 
            "bodywash",
            "towels",
            "wash cloths",
            "paper towels",
            "toilet tissues",
            "tissues", 
            "toilet paper",
            "kleenex",
            "paper products",
            "paper cups", 
            "paper plates",
            "paper bowls",
            "plastic forks" ,
            "plastic spoons",
            "plastic knives",
            "plastic silverware",
            "plastic tableware",
            "disposable forks",
            "disposable spoons",
            "disposable knives",
            "disposable silverware",
            "disposable tableware",
            "dish soap",
            "Clorox cleaning wipes",
            "cleaning wipes",
            "wipes",
            "antibacterial wipes",
            "baby wipes",
            "new crib sheets",
            "size 4 diapers",
            "ethnic hair products",
            "creme of nature shampoo",
            "creme of nature conditioner",
            "creme of nature edge control",
            "shea moisture shampoo",
            "shea moisture conditioner",
            "shea moisture curl enhancing smoothie",
            "pantene shampoo",
            "pantene conditioner",
            "hask shampoo",
            "hask conditioner",
            "ogx shampoo",
            "ogx conditioner",
            "maui moisture shampoo",
            "maui moisture conditioner",
            "perfect results shampoo",
            "perfect results conditioner",
            "perfect results grease",
            "salon pro hair food",
            "salon pro grease",
            "olive oil edge control",
            "olive oil grease",
            "olive oil moisturizer",
            "eco styler gel",
            "wide tooth combs",
            "hard bristle brushes",
            "used cell phones",
            "cell phones"
        ],
        donationMethod: "Call for drop-off times and instructions. Contact Lynette at lreddick @dvcac.org or 216-229-2420."
    },
    {
        name: "Hitchcock Center for Women, Inc.",
        thumbnail: "http://hcfw.org/wp-content/uploads/2017/07/hcfw-logo.png",
        href: "http://hcfw.org/",
        address: "1227 Ansel Rd.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44108",
        phone: "216-421-0662",
        EIN: "34-1264097",
        mainCause:"Residential substance abuse for women and children",
        causes: [
            "women",
            "recovery",
            "addiction",
            "substance abuse",
            "alcohol abuse",
            "drug treatment",
            "alcohol treatment",
            "mental health",
            "mental health treatment",
        ],
        mission: "To wholistically empower women to achieve and maintain productive, chemically free lives at home, work, and in the community.",
        contactEmail: "info@hcfw.org",
        acceptedItems: [
            "nitrile gloves",
            "fleece blanket",
            "travel blanket",
            "blanket",
            "crayons",
            "diapers",
            "similac",
            "baby formula",
            "kids hats",
            "beanies",
            "winter hats",
            "kids winter hats",
            "diaper",
            "kids gloves",
            "winter gloves",
            "winter jackets",
            "kids jackets",
            "winter jacket",
            "kids jacket",
            "girls jacket",
            "boys jacket",
            "winter fleece",
            "fleece",
            "kids fleece",
            "kids winter clothing",
            "puzzle books",
            "crossword puzzles",
            "sudoku",
            "search word",
            "shower caddy",
            "flip flops",
            "shower shoes",
            "pocket planner",
            "planner",
            "planners",
            "crochet hook",
            "crochet hooks",
            "knitting needles",
            "knitting needle",
            "yarn",
            "winter headbands",
            "women's gloves",
            "gloves",
            "winter gloves",
            "winter hats",
            "winter clothing",
            "nail file",
            "nail files",
            "emery boards",
            "emery board",
            "hair brushes",
            "hairbrushes",
            "comb",
            "combs",
            "wig scarves",
            "headbands",
            "bath sponges",
            "mesh pouf",
            "shower pouf",
            "loofah",
            "deodorant",
            "antiperspirant",
            "shampoo",
            "conditioner",
            "silk scrunchies",
            "hair scrunchies",
            "towels",
            "bath towels",
            "towel",
            "bath towel",
            "lotion",
            "hand lotion",
            "body lotion",
            "body wash",
            "shower gel"
            ],
        donationMethod: "Contact info@hcfw.org for information about donation delivery."
    },
    {
        name: "The City Mission",
        thumbnail: "https://www.thecitymission.org/wp-content/uploads/2018/04/logo.png",
        href: "https://www.thecitymission.org/",
        address: "5310 Carnegie Ave.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44103",
        phone: "216-431-3510",
        EIN: "34-0760586",
        mainCause:"Human services",
        causes: [
            "homeless",
            "homeless shelter",
            "homeless shelters",
            "human services",
            "christianity",
            "shelter",
            "trauma",
            "poverty"],
        mission: "To provide help and hope to all people through the transforming power of God's love.",
        contactEmail: "",
        acceptedItems: [
            "walker",
            "baby walker",
            "sports bras",
            "bus ticket",
            "bus tickets",
            "bible",
            "bibles",
            "winter clothing",
            "men's winter clothing",
            "women's winter clothing",
            "children's winter clothing",
            "socks",
            "men's socks",
            "women's socks",
            "children's socks",
            "underwear",
            "men's underwear",
            "women's underwear",
            "children's underwear",
            "t-shirts",
            "men's t-shirts",
            "women's t-shirts",
            "children's t-shirts",
            "pillows",
            "twin sheets",
            "twin blankets",
            "shower curtains",
            "towels",
            "wash cloths",
            "bath towels",
            "hand towels",
            "ibuprofen",
            "advil",
            "tylenol",
            "acetaminophen",
            "cold medicine",
            "cold medication",
            "cough drops",
            "cough medicine",
            "cough medication",
            "kids movies",
            "kids DVDs",
            "craft supplies",
            "tissue paper",
            "construction paper",
            "poster paints",
            "glitter paint",
            "googley eyes",
            "markers",
            "diapers",
            "wipes",
            "baby wipes",
            "strollers",
            "stroller",
            "double stroller",
            "double strollers",
            "double-stroller",
            "play pen",
            "pack n' play",
            "bassinette",
            "shampoo",
            "conditioner",
            "body wash",
            "soap",
            "deodorant",
            "toothpaste",
            "toothbrush",
            "feminine hygiene products",
            "tampons",
            "baby wash",
            "baby soap",
            "vaseline",
            "ethnic hair",
            "ethnic hair products",
            "bath and body works",
            "jewelry",
            "costume jewelry",
            "gift cards",
            "calendars",
            "planners",
            "pocket calendars",
            "journals",
            "devotionals",
            "razors",
            "saving cream",
            "comb",
            "combs",
            "razor",
            "after shave",
            "aftershave",
            "cologne",
            "backpacks",
            "backpack",
            "duffel bags",
            "duffel bag",
            "shower shoes",
            "flip flops",
            "dress shirt",
            "dress shirts",
            "shirts",
            "polo shirts",
            "polo shirt",
            "wallet",
            "wallets",
            "sports gear",
            "Cleveland sports gear",
            "school supplies",
            "baby formula",
            "diapers",
            "toiletries",
            "clothing",
            "furniture",
            "couch",
            "couches",
            "bed frames",
            "coffee tables",
            "bedding",
            "dresser",
            "dressers",
            "oven",
            "stove",
            "refrigerator",
            "microwave",
            "coffee maker",
            "kitchen utensils",
            "pots",
            "pans",
            "dishes",
            "electronics",
            "tv",
            "dvd players",
            "outdoor equipment",
            "shovel",
            "snow shovel",
            "lawnmower",
            "maintenance supplies",
            "appliances",
            ],
        donationMethod: "Donations are currently accepted Monday through Friday from 10:00 a.m. to 4:00 p.m. at 5310 Carnegie Avenue, Cleveland."
    },
    {
        name: "L'Arche Cleveland",
        thumbnail: "https://www.larchecleveland.org/wp-content/uploads/2020/06/LArche-Cleveland-Online.png",
        href: "https://www.larchecleveland.org/",
        address: "11811 Shaker Blvd. Ste 116",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44120",
        phone: "216-721-2614",
        EIN: "34-1193618",
        mainCause:"Group homes for the disabled",
        causes: [
            "shelter care",
            "residential care",
            "shelter",
            "group home",
            "disabilities",
            "disabled",
            "disabled adults",
            "intellectual disabilities"],
        mission: "L'Arche Cleveland, Inc is a not for profit, faith-based community agency which provides homes and services to adults with intellectual and developmental disabilities.",
        contactEmail: "office@larchecleveland.org",
        acceptedItems: [
            "masks",
            "disposable masks",
            "reusable masks",
            "hand sanitizer",
            "bleach",
            "disinfectant",
            "wipes",
            "antibacterial wipes",
            "gift cards",
            "twin bedding",
            "bedding",
            "towels",
            "bath towels",
            "hand towels",
            "kitchen towels",
            "towels",
            "throw blankets",
            "blanket",
            "blankets",
            "rice cooker",
            "slow cooker",
            "rice steamer",
            "crock pot",
            "sitting chair",
            "chair",
            "chairs"
        ],
        donationMethod: "L'Arche will arrange pick-up or porch drop-off at one of our locations. Please contact Alex at alex@larchecleveland.org or 216-721-2614 to schedule pick-up."
    },
    {
        name: "Talespinner Children's Theatre",
        thumbnail: "https://www.talespinnerchildrenstheatre.org/images/tct-logo.png",
        href: "https://www.talespinnerchildrenstheatre.org/",
        address: "5209 Detroit Avenue",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44102",
        phone: "216-264-9680",
        EIN: "45-3334641",
        mainCause:"Arts and Culture for children",
        
        causes: [
            "arts",
            "cuture",
            "arts and culture",
            "theater",
            "performing arts",
            "performing arts education",
            "education",
            "special needs education",
            "multicultural education",
            "children",
            "youth",
            "families",
            "immigrants",
            "migrants",
            "poverty",
            "economically disadvantaged people"],
        mission: "Talespinner Children's Theatre develops and produces highly imaginative, original, collaborative and interactive professional works for children that also stimulate creative growth in its artists. These pieces involve acting, dance, music, puppetry, and numerous other artistic disciplines, and are open to all creative possibility. TCT creates work that remembers that children are smaller people, not lesser people. Talespinner Children's Theater strives to reach across socio-economic, cultural and traditional boundaries to help awaken and bring better understanding by opening eyes, ears, hearts and imaginations in the young people (and artists) of Cleveland and its surrounds.",
        contactEmail: "info@talespinnerchildrenstheater.org",
        acceptedItems: [
            "book shelves",
            "utility shelves",
            "storage bins",
            "rolling carts",
            "tool cabinet",
            "yoga mats",
            "floor mats",
            "runners",
            "vaccuum",
            "vaccuum cleaner",
            "shop vac",
            "extension cord",
            "extension cords",
            "power strip",
            "power strips",
            "gift cards"],
        donationMethod: "Contact us for pick-up of local donations. Items may also be delivered directly to the theater at 5209 Detroit Avenue, Cleveland."
    },
    {
        name: "Neighborhood Pets Outreach & Resource Center",
        thumbnail: "http://www.neighborhoodpetscle.org/uploads/7/7/9/8/77980490/nhood-pets-logo-color.jpg",
        href: "http://www.neighborhoodpetscle.org/",
        address: "3711 East 65th St.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44105",
        phone: "216-505-5853",
        EIN: "27-2026307",
        mainCause:"Animal Welfare",
        causes: [
            "animals",
            "pets",
            "domesticated animals",
            "animal welfare",
            "human services"],
        mission: "Neighborhood Pets recognizes the many benefits of the human animal bond, and supports people with financial needs by helping them keep their pets in their homes. We do this by providing access to affordable pet care, resources, information and other supportive services. Our welcoming environment is designed to foster trust and create long-lasting relationships as we build community.",
        contactEmail: "info@neighborhoodpetscle.org",
        acceptedItems: [
            "dry cat food",
            "cat food",
            "canned cat food",
            "cat treats",
            "scratching pads",
            "scratching posts",
            "cat litter",
            "clumping cat litter",
            "cat collars",
            "breakaway cat collars",
            "cat carriers",
            "cat beds",
            "feliway spray",
            "dog food",
            "dry dog food",
            "dog treats",
            "kongs",
            "nylabones",
            "slow-feed bowls",
            "jolly balls",
            "durable soft toys",
            "dog beds",
            "pet beds",
            "martingale collars",
            "dog leashes",
            "freedom harness",
            "easy walk harness",
            "creamy peanut butter",
            "spray cheese",
            "gift cards",
            "bleach",
            "paper towels",
            "towels",
            "all-purpose cleaner",
            "copy paper",
            "printer paper",
            "envelopes",
            "stamps",
            "storage tubs",
            "freezer bags",
            "address labels",
            "shipping labels",
            "bottled water", 
            "pop-up tents",
            "folding table",
            "folding tables",
            "folding chair",
            "folding chairs",
            "id tag engraving machine",
            "laptops",
            "laptop",
            "iPad",
            "iPads",
            "otoscope",
            "microscope"
            ],
        donationMethod: "Donations may be dropped off at our Slavic Village location (3711 E 65th St. Cleveland, OH) on Tuesdays & Thursdays between noon and 4:00 p.m., and Saturdays between 10:00 a.m. and 2:00 p.m. Contact us at info@neighborhoodpetscle.org or 216-505-5853 to schedule drop-off during other times."
    },

    {  name: "Providence House",
        thumbnail: "https://www.provhouse.org/images/ph_logo.png",
        href: "https://www.provhouse.org/",
        address: "2050 West 32nd St.",
        city: "Cleveland",
        state: "OH",
        zipCode: "44113",
        phone: "216-651-5982",
        EIN: "34-1336325",
        mainCause:"Emergency Family Shelter",
        causes: ["children",
            "families",
            "crisis intervention",
            "emergency shelter",
            "crisis nursery",
            "family trauma services",
            "case management",
            "community education",
            "parenting support",
            "parenting education"
        ],
        mission: "Providence House protects at-risk children and supports families through crisis, strengthening communities to end child abuse and neglect.",
        contactEmail: "emilyb@provhouse.org",
        acceptedItems: [
            "paper towels", 
            "liquid hand soap", 
            "clorox wipes", 
            "antibacterial wipes", 
            "spray bottles", 
            "disposable cups", 
            "disposable plates", 
            "cloth face masks", 
            "diapers", 
            "unscented baby wipes", 
            "baby lotion", 
            "baby wash", 
            "baby soap", 
            "baby shampoo", 
            "cream of nature argan oil shampoo", 
            "tylenol", 
            "acetaminophen", 
            "advil", 
            "ibuprofen", 
            "motrin", 
            "hydrocortisone", 
            "aquafor", 
            "nasal saline", 
            "miralax", 
            "debrox ear drops", 
            "flinstones chewable multivitamins", 
            "genteal eye drops", 
            "cetirizine", 
            "zyrtec", 
            "toys", 
            "nintendo switch", 
            "nintendo switch games", 
            "book bags", 
            "children's suitcases", 
            "gift cards", 
            "baby formula", 
            "gerber good start formula", 
            "similac formula", 
            "hand soap", 
            "liquid hand soap", 
            "dishwashing liquid", 
            "bleach", 
            "garbage bags", 
            "humidifiers", 
            "first aid kits", 
            "groceries", 
            "canned fruit", 
            "canned vegetables", 
            "crackers", 
            "cheese crackers", 
            "popcorn", 
            "applesauce", 
            "cookies", 
            "condiments", 
            "ranch dressing", 
            "pudding", 
            "pudding cups", 
            "jell-O", 
            "graham crackers", 
            "saltine crackers", 
            "pediasure"],
        donationMethod: "Donations should be scheduled Monday through Friday, 9:30am-4:30 p.m.  Please call 216-651-5982 to schedule."
   },
    {   name: "Access, Inc.",
        thumbnail: "https://www.access-shelter.org/images/access-logo.png",
        href: "https://www.access-shelter.org/",
        address: "P.O. Box 1007",
        city: "Akron",
        state: "OH",
        zipCode: "44309",
        phone: "330-535-2999",
        EIN: "",
        mainCause:"Emergency Family Shelter",
        causes: [
            "homeless shelter", 
            "women", 
            "children", 
            "poverty",
            "housing", 
            "emergency housing", 
            "transitional housing", 
            "health", 
            "wellness", 
            "childcare", 
            "aftercare", 
            "hunger", 
            "hunger relief", 
            "employment"
    ],
        mission: "ACCESS is dedicated to addressing the plight of homeless women and children in our community. The agency encourages the development of self-esteem and the attainment of self-sufficiency through its commitment of providing a holistic, safe and supportive environment, and through its programs of housing, advocacy, and empowerment.",
        contactEmail: "",
        acceptedItems: [
            "baby items", 
            "diapers", 
            "bottles", 
            "baby bottles", 
            "onesies", 
            "formula", 
            "baby formula", 
            "baby wipes", 
            "wipes", 
            "clothing", 
            "underwear", 
            "bras", 
            "winter coats", 
            "shoes", 
            "boots", 
            "slippers", 
            "toiletries", 
            "pillows", 
            "bedding", 
            "twin bedding", 
            "blankets", 
            "twin blankets", 
            "vaseline", 
            "lotion", 
            "jergen's", 
            "planners", 
            "meditation books", 
            "umbrellas", 
            "folding umbrellas", 
            "adult activity books", 
            "adult coloring books"
    ],
        donationMethod: "Call for drop-off hours and location. Only accepting new items."
    },
    {
        name: "Amvets of Ohio",
        thumbnail: "http://www.amvetsclothingpickup.org/site_templates/amvets_ohio/images/AMVETS_Website_05.gif",
        href: "https://www.ohamvets.org/",
        address: "960 Checkrein Ave.",
        city: "Columbus",
        state: "OH",
        zipCode: "43229",
        phone: "866-388-0046",
        EIN: "34-0943286",
        mainCause: "Veterans Services",
        causes: ["Veterans Services"],
        mission: "To enhance and safeguard the entitlements for all American Veterans who have served honorably and to imporve the quality of life for them, their families, and the communities where they live through leadership, advocacy, and services.",
        contactEmail: "",
        acceptedItems: [
            "appliances", 
            "small appliances", 
            "area rugs", 
            "backpacks", 
            "baseball equipment", 
            "basketballs", 
            "bikes", 
            "mountain bikes", 
            "bedding", 
            "bed spreads", 
            "blankets", 
            "books", 
            "novels", 
            "children's books", 
            "cookbooks", 
            "cameras", 
            "camping equipment", 
            "can openers", 
            "canister sets", 
            "cassette tapes", 
            "CDs", 
            "compact discs", "ceramics", "clocks", "clothing", "collectables", "dishes", "china", "dolls", "fabric", "material", "fans", "figure skates", "ice skates", "flags", "flatware", "lamps", "floor lamps", "shades", "garden tools", "glassware", "gloves", "golf clubs", "golf balls", "golf bags", "purses", "handbags", "hockey equipment", "jewelry", "life jackets", "luggage", "mirrors", "mixers", "magazine racks", "paintings", "photos", "pictures", "frames", "paperback books", "pots", "pans", "household items", "power tools", "hand tools", "racquetball equipment", "radios", "records", "albums", "record albums", "roller blades", "scuba diving equiment", "scuba gear", "scuba equipment", "sewing machine", "sheets", "shoes", "soccer equipment", "sporting goods", "sports bags", "tennis equiment", "toaster", "toaster oven", "towels", "toys", "tv trays", "vacuum cleaners", "volleyballs", "canes", "walking canes", "walking sticks", "wheel chairs", "yarn"
    ],
        donationMethod: "Go to amvetsclothingpickup.org to schedule your donation pick-up."
         },
    {
     name: "Fairmount Center for the Arts",
     thumbnail: "https://www.fairmountcenter.org/wp-content/uploads/2019/10/cropped-logo.jpg",
     href: "https://www.fairmountcenter.org",
     address: "8400 Fairmount Road",
     city: "Novelty",
     state: "OH",
     zipCode: "44072",
     phone: "440-338-3171",
     EIN: "23-7199754",
     mainCause:"Enriching Lives Through the Arts",
     causes: [
        "arts",
        "children",
        "seniors",
        "classes",
        "workshops",
        "art education",
        "music",
        "music education"],
     mission: "Fairmount Center for the Arts fosters a love for the arts in a noncompetitive environment with programs preschoolers to senior citizens. Our programs aim to challenge, enrich and nurture, allowing each student to thrive as a creative individual.",
     contactEmail: "info@fairmountcenter.org",
     acceptedItems: [
         "arts & crafs supplies",
,         "computer equipment",
         "furniture",
         "desks",
         "file cabinets",
         "office equipment",
         "office supplies",
         "calculators",
         "pencils",
         "pens",
         "paper"
        ],
     donationMethod: "Call for drop-off hours. Pick-up may be available."
 },  
 {
    name: "Friendship Animal Protective League",
    thumbnail: "https://friendshipapl.org/wp-content/uploads/2016/06/logo-sm.png",
    href: "http://www.friendshipAPL.org",
    address: "8303 Murray Ridge Road",
    city: "Elyria",
    state: "OH",
    zipCode: "44035",
    phone: "440-322-4321",
    EIN: "34-6529498",
    mainCause:"Animal Adoption Services",
    causes: [
        "animals",
        "animal adoption",
        "animal abuse",
        "animal welfare",
        "animal shelter",
        "pets",
        "pet adoption"],
    mission: "Friendship APL is a private, independent, non-profit [501(c)(3)] humane society founded in Elyria, Ohio in 1957. We own and operate the largest animal shelter in Lorain County. Our members incorporated on August 30, 1957 as the Lorain County Animal Protective League. We changed our name to Friendship Animal Protective League on October 30, 2005.",
    contactEmail: "gregory@friendshipapl.org",
    acceptedItems: [
        "appliances",
        "blender",
        "refrigerator",
        "washer",
        "dryer",
        "computer equipment",
        "gardening supplies",
        "shovels",
        "rakes",
        "trowels",
        "gloves",
        "household goods",
        "tables",
        "chairs",
        "medical equipment",
        "medical supplies",
        "surgical instruments",
        "gauze",
        "bandages",
        "syringes",
        "sponges",
        "incubator",
        "newspapers",
        "office equipment",
        "office supplies",
        "pet food",
        "pet supplies",
        "tools",
        "cars"
        ],
    donationMethod: "Drop-off Monday throught Saturday, 9:00 a.m. through 4:30 p.m, and Sunday from 10:00a.m. through 2:30 p.m. Pick-up may be available. Please call for more information."
},
{
    name: "My Fairy Godmother, Inc.",
    thumbnail: "https://e7.pngegg.com/pngimages/817/51/png-clipart-charitable-organization-computer-icons-donation-charity-others-love-miscellaneous-thumbnail.png",
    href: "https://www.facebook.com/MFGMOhio/",
    address: "P.O. Box 46508",
    city: "Cleveland",
    state: "OH",
    zipCode: "44146",
    phone: "216-475-1430",
    EIN: "34-1947155",
    mainCause:"Formal Wear for High Schoolers",
    causes: [
        "children",
        "teenagers",
        "poverty"],
    mission: "Provides gently-worn or new formal dresses and accessories to high school students that lack the financial resources to purchase attire for their formal event.",
    contactEmail: "donatedresses@hotmail.com",
    acceptedItems: [
        "clothing",
        "formal dresses",
        "new hosiery",
        "dress shoes",
        "garment bags",
        "garment racks",
        "jewelry",
        "toiletries",
        "new cosmetics"],
    donationMethod: "For more information or to make a donation, contact donatedresses@hotmail.com"
},
{
    name: "New Avenues to Independence, Inc.",
    thumbnail: "https://static.wixstatic.com/media/2ce139_18d2db4e8c67405f9f8d28347146ff7b~mv2.png/v1/fill/w_544,h_316,al_c,q_85,usm_0.66_1.00_0.01/New%2520Ave_edited.webp",
    href: "https://www.newavenues.net/",
    address: "17608 Euclid Ave.",
    city: "Cleveland",
    state: "OH",
    zipCode: "44112",
    phone: "216-481-1909",
    EIN: "34-0871661",
    mainCause:"Disability Services",
    causes: [
        "disability services",
        "human services",
        "social services",
        "support services"],
    mission: "The mission of New Avenues to Independence is to provide opportunities for people with disabilities and special needs to become more independent and productive members of society by offering the highest quality support services and developing innovative and inclusive programs.",
    contactEmail: "hello@newavenues.net",
    acceptedItems: [
        "appliances",
        "arts & crafts supplies",
        "baby items",
        "bicycles",
        "books",
        "magazines",
        "building materials",
        "cleaning supplies",
        "clothing",
        "computer equipment",
        "eyeglasses",
        "furniture",
        "gardening supplies",
        "household goods",
        "jewelry",
        "medical equipment & supplies",
        "musical instruments",
        "office equipment",
        "office supplies",
        "paint",
        "school supplies",
        "sporting goods",
        "tools",
        "toys",
        "games"],
    donationMethod: "Call 216-481-1910 ext. 221 to make an appointment for drop-off."
},
{
    name: "Stearns Homestead",
    thumbnail: "https://e7.pngegg.com/pngimages/817/51/png-clipart-charitable-organization-computer-icons-donation-charity-others-love-miscellaneous-thumbnail.png",
    href: "http://www.stearnshomestead.com/",
    address: "6975 Ridge Rd.",
    city: "Parma",
    state: "OH",
    zipCode: "44129",
    phone: "440-888-5766",
    EIN: "",
    mainCause:"Educational Farm",
    causes: [
        "farming",
        "agriculture",
        "farming education",
        "agriculltural education",
        "animal welfare"],
    mission: "Stearns Homestead Farm is a 48-acre farm owned by the City of Parma and operated by the Parma Area Historical Society. The farm animals and shelters are part of the last operating farm in Parma, Ohio.",
    contactEmail: "stearnshomestead@gmail.com",
    acceptedItems: [
        "cleaning supplies",
        "paper towels",
        "food",
        "Cheerios",
        "carrots",
        "lettuce",
        "red applies",
        "gardening supplies",
        "straw",
        "animal bedding",
        "household goods",
        "towels",
        "metal bowls",
        "ceramic bowls",
        "pet food",
        "pet supplies",
        "cat food",
        "tools"],
    donationMethod: "Call for more information."
},
{
    name: "Youth Challenge",
    thumbnail: "https://www.youthchallengesports.com/wp-content/themes/youthchallengesports/images/logo.png",
    href: "https://www.youthchallengesports.com/",
    address: "800 Sharon Drive",
    city: "Westlake",
    state: "OH",
    zipCode: "44145",
    phone: "440-892-1001",
    EIN: "34-1396825",
    mainCause:"Sports and Recreation for Children with Physical Disabilities",
    causes: [
        "recreation",
        "sports",
        "youth",
        "disabled",
        "disabilities"],
    mission: "Youth Challenge brings together young people with physical disabilities and teen volunteers who inspire each other through adapted sports, recreation and social growth activities.",
    contactEmail: "yc@youthchallengesports.com",
    acceptedItems: [
        "arts & craft supplies",
        "musical instruments",
        "sporting goods"],
    donationMethod: "Call for drop-off information. Pick-up may be available."
},
   {
     name: "Womankind Care Center",
     thumbnail: "https://womankindcleveland.org/wp-content/uploads/2020/01/Womankind-logo.png",
     href: "https://womankindcleveland.org/",
     address: "5350 Transportation Blvd., Suite 18",
     city: "Garfield Heights",
     state: "OH",
     zipCode: "44125",
     phone: "216-662-5700",
     EIN: "51-0168651",
     mainCause:"Free Prenatal Care and Support",
     causes: [
        "women",
        "women's health",
        "prenatal care",
        "medical care",
        "obstetrics",
        "health and human services"
    ],
     mission: "To provide hope, help, and possibility to any pregnant woman by offering comprehensive integrative care in a loving, nonjudgmental environment.",
     contactEmail: "nilg@womankindcleveland.org",
     acceptedItems: [
         "diapers",
        "baby wipes",
        "baby formula",
        "cribs",
        "baby clothing",
        "toddler clothing",
        "maternity clothing",
        "car seats",
        "strollers",
        "playpens",
        "high chairs"],
     donationMethod: "For further information on appropriate donation items, please contact Womankind at 216-662-5700."
 },
    {
     name: "Ohio City Bicycle Co-Op",
     thumbnail: "https://ohiocitycycles.org/wp-content/uploads/2020/04/frontpage6.png",
     href: "https://ohiocitycycles.org/",
     address: "1840 Columbus Rd.",
     city: "Cleveland",
     state: "OH",
     zipCode: "44113",
     phone: "216-830-2667",
     EIN: "51-0453375",
     mainCause:"Access to Bicycles",
     causes: [
        "bicycling",
        "cycling",
        "recreation",
        "health",
        "wellness"],
     mission: "The mission of the Ohio City Bicycle Co-op (OCBC) is to promote the use of bicycles in greater Cleveland and engage area youth and adults in cycling activities that foster independence, resourcefulness, and good health. The OCBC works to accomplish this by offering safe cycling and bike repair education, Earn A Bike programs, and a consumer’s cooperative bike shop; by providing dependable used bikes and accessories; and by producing cycling events and tours that impart skills while encouraging riding for fun, fitness and practical transportation.",
     contactEmail: "info@ohiocitycycles.org",
     acceptedItems: [
        "bicycles",
        "bicycle-related materials",
        "bicycle equipment",
        "bicycle parts",
        "bicycle accessories",
        "helmets",
        "tools"],
     donationMethod: "You can bring your donations to our location in the Flats anytime we’re open, or you can call or email to make arrangements if those times are not convenient – someone is usually in Tuesday through Saturday from 10-6pm."
 },
 {
    name: "Northeast Ohio Coalition for the Homeless",
    thumbnail: "https://images.squarespace-cdn.com/content/59e6491b9f8dce817446bdc6/1509553211182-IYLK0LPH007A2XUOO6PI/Picture1.png?content-type=image%2Fpng",
    href: "https://www.neoch.org/",
    address: "3631 Perkins Ave., #3A-3",
    city: "Cleveland",
    state: "OH",
    zipCode: "44114",
    phone: "216-432-0540",
    EIN: "https://www.neoch.org/",
    mainCause:"Shelter and Services for the Homeless",
    causes: [
        "homeless",
        "homelessness",
        "hunger",
        "shelter",
        "housing"],
    mission: "Since 1988, NEOCH has sought to break the cycle of homelessness in Northeast Ohio. We exist to eliminate the root causes of homelessness while loving our diverse community through organizing, advocacy, education, and street outreach.",
    contactEmail: "neoch@neoch.org",
    acceptedItems: [
        "socks",
        "tents",
        "sleeping bags",
        "hygiene kits",
        "gloves",
        "hats",
        "backpacks",
        "underwear",
        "long underwear",
        "bus tickets",
        "blankets",
        "towels",
        "tissues",
        "baby wipes",
        "hand sanitizer",
        "bug spray",
        "sunscreen",
        "rain ponchos"
    ],
    donationMethod: "If you have any of these items, please call (216) 432-0540 or bring them to our office at 3631 Perkins Ave., Suite 3A-3 from Monday-Friday between 9am - 5pm."
},
{
    name: "Noah's Lost Ark Exotic Animal Sanctuary",
    thumbnail: "http://noahslostark.org/images/NoahsLostArkLogo.png",
    href: "http://noahslostark.org/",
    address: "8424 Bedell Road",
    city: "Berlin Center",
    state: "OH",
    zipCode: "44401",
    phone: "330-584-7835",
    EIN: "34-1934016",
    mainCause:"Exotic Animal Santuary",
    causes: [
        "animal welfare",
        "animal sanctuary",
        "animal shelter"],
    mission: "Noah's Lost Ark is committed to educating people everywhere of the escalating epidemic of neglected, abused and unwanted exotic animals.  By model of bestowing safe havens for mistreated exotic animals, along with educational programs, Noah's Lost Ark is instilling compassion, respect and responsibility towards the preservation and conservation of all animals, ultimately safeguarding the natural environment for future generations.",
    contactEmail: "noahslostark@aol.com",
    acceptedItems: [
        "garden supplies",
        "backhoe",
        "straw",
        "hay",
        "tractor repair supplies",
        "gas powered welder",
        "chain saws",
        "garden hoses",
        "rakes",
        "shovels",
        "water buckets",
        "feed buckets",
        "wheelbarrows",
        "skid loaders",
        "computer",
        "copy paper",
        "printing services",
        "postage stamps",
        "office supplies",
        "building supplies",
        "screws",
        "stains",
        "sprayers",
        "concrete",
        "plywood",
        "lumber",
        "chains",
        "clips",
        "fending",
        "fence posts",
        "roofing",
        "electrical supplies",
        "freezer",
        "refrigerator",
        "vehicles",
        "appliances",
        "boomer balls",
        "children's hard plastic toys",
        "big cat toys",
        "disposable gloves",
        "dog food",
        "cat food", 
        "produce",
        "poultry",
        "work boots",
        "work gloves",
        "hand tools",
        "heat lamps",
        "igloo dog houses",
        "calf hutches",
        "landscaping materials",
        "sand",
        "gravel",
        "trees",
        "shrubs", 
        "flowers",
        "sawdust",
        "bleach"],
    donationMethod: "Please email noahslostark@aol.com or call 330-584-7835 for more information."
},
{
    name: "Karamu House, Inc.",
    thumbnail: "https://res-3.cloudinary.com/crunchbase-production/image/upload/c_lpad,f_auto,q_auto:eco/xvpk81fweaev0aap5fur",
    href: "https://www.karamuhouse.org/",
    address: "2355 East 89th St.",
    city: "Cleveland",
    state: "OH",
    EIN: "44106",
    mainCause:"Theater and Arts Honoring the African American Experience",
    causes: [
        "theater",
        "arts",
        "education",
        "dance",
    ],
    mission: "Founded in 1915, Karamu House is a place of joyful gathering (the meaning of ‘Karamu” in Swahili), where people from different races, religions, and economic backgrounds come together through the arts. Recognized as the oldest, producing African American theatre in the nation, Karamu House is continually cited as one of Cleveland’s top four treasures—and featured in the Smithsonian National Museum of African American History & Culture and listed on the U.S. National Register of Historic Places.  ",
    contactEmail: "ctix@karamuhouse.org",
    acceptedItems: [
        "art supplies",
        "craft supplies",
        "furniture",
        "paint"],
    donationMethod: "Call for more information."
},
{
    name: "Hunger Network of Greater Cleveland",
    thumbnail: "https://717031.smushcdn.com/1674875/wp-content/uploads/2020/03/HNGC-Logo-Color-Small1.png?lossy=1&strip=1&webp=1",
    href: "https://hungernetwork.org/",
    address: "614 West Superior Avenue, Suite 744",
    city: "Cleveland",
    state: "OH",
    zipCode: "44113",
    phone: "216-619-8155",
    EIN: "34-1810545",
    mainCause:"Food and Services for the Hungry",
    causes: [
        "hunger",
        "poverty",
        "human services",
        "social services"],
    mission: "The mission of Hunger Resource Network is to aid in the alleviation of hunger by coordinating the procurement and distribution of food to those in need through community outreach events benefiting food pantries, soup kitchens and shelters.",
    contactEmail: "help@hungernetwork.org",
    acceptedItems: [
        "non-perishable food"],
    donationMethod: "Call to drop-off at one of our 54 locations. Hours vary."
},
{
    name: "Horizon Education Centers",
    thumbnail: "https://www.horizoneducationcenters.org/hubfs/footer-logomain.png",
    href: "https://www.horizoneducationcenters.org/",
    address: "25300 Lorain Rd.",
    city: "North Olmsted",
    state: "OH",
    zipCode: "44070",
    phone: "440-779-1930",
    EIN: "34-1267458",
    mainCause: "Childcare, Education, and Youth Development",
    causes: [
        "affordable child care",
        "childcare",
        "ducation",
        "childhood recreation"],
    mission: "Our mission is to provide high-quality early childhood education, care and youth development programs. We provide affordable care including educational curriculums and enrichment opportunities for children ages 6 weeks to 12 years in Western Cuyahoga County and Lorain County since 1978.",
    contactEmail: "",
    acceptedItems: [
        "art supplies",
        "craft supplies",
        "books",
        "computer equipment",
        "gardening supplies",
        "musical instruments",
        "office equipment",
        "office supplies",
        "school supplies",
        "sporting goods",
        "toys",
        "games"
    ],
    donationMethod: "Call for drop-off hours. Pick-up may be available."
},
{
    name: "First Tee Cleveland",
    thumbnail: "https://www.firstteecleveland.org/wp-content/uploads/sites/9/2020/08/2020_FT_Web_0122_RGB_cleveland_Green.png",
    href: "https://www.firstteecleveland.org/",
    address: "3841 Washington Park Blvd.",
    city: "Newburgh Heights",
    state: "OH",
    zipCode: "44105",
    phone: "216-641-7799",
    EIN: "34-1915692",
    mainCause:"Youth Golf Program",
    causes: [
        "golf",
        "youth recereation",
        "youth programs"],
    mission: "The mission of First Tee – Cleveland is to impact the lives of young people by providing educational programs that build character, instill life-enhancing values and promote healthy choices through the game of golf.",
    contactEmail: "plopresti@firstteecleveland.org",
    acceptedItems: [
        "golf equipment",
        "toys",
        "games"
    ],
    donationMethod: "Call for more information."
},
{
    name: "Cleveland Sight Center",
    thumbnail: "https://www.clevelandsightcenter.org/sites/all/themes/csc/logo.png",
    href: "https://www.clevelandsightcenter.org/",
    address: "1909 East 101st St.",
    city: "Cleveland",
    state: "OH",
    zipCode: "44106",
    phone: "216-791-8118",
    EIN: "34-0714652",
    mainCause:"Services for the Visually Impaired",
    causes: [
        "blind",
        "vision",
        "disability",
        "disabled services",
        "human services"],
    mission: "Our goal is to enable those who are blind or have low vision to achieve independence. We educate, empower and employ; providing training and guidance to our clients and the communities we serve.",
    contactEmail: "info@clevelandsightcenter.org",
    acceptedItems: ["eyeglasses"],
    donationMethod: "Drop-off at 1909 East 101st St. in Cleveland or at any Cuyahoga County Library branch"
},
{
    name: "Cleveland Furniture Bank",
    thumbnail: "http://clevelandfurniturebank.org/wp-content/uploads/2017/02/logo1.gif",
    href: "http://clevelandfurniturebank.org/",
    address: "13360 Smith Road",
    city: "Cleveland",
    state: "OH",
    zipCode: "44130",
    phone: "216-459-2265",
    EIN: "56-2610534",
    mainCause:"Providing basic home furnishings to those in need in Northeast Ohio.",
    causes: [
        "poverty",
        "human services"],
    mission: "We provide furniture and mattresses to people in need who seek to establish a stable place to live.",
    contactEmail: "tom@clevelandfurniturebank.org",
    acceptedItems: [
        "appliances",
        "furniture",
        "household goods"],
    donationMethod: "Call 216-459-2265 ext. 101 to make a donation."
}
]
db.Charity.remove({})
  .then(() => db.Charity.collection.insertMany(charitySeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });

//   {
//     name: "",
//     thumbnail: "",
//     href: "",
//     address: "",
//     city: "",
//     state: "",
//     zipCode: "",
//     phone: "",
//     EIN: "",
//     mainCause:"",
//     causes: [""],
//     mission: "",
//     contactEmail: "",
//     acceptedItems: [""],
//     donationMethod: ""
// }