const mongoose = require("mongoose");
const db = require("../models");

//need file to empty the Charity collection and insert charities below??

mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/Charity"
  );

const charitySeed = [
    {
        name: "Edna House",
        thumbnail: "https://www.guidestar.org/ViewEdoc.aspx?eDocId=6169876&approved=True",
        href: "www.ednahouse.org",
        address: "2007 West 65th Street",
        city: "Cleveland",
        state: "Ohio",
        zipCode: 44102,
        phone: "216-281-7751",
        EIN: "14-1912872",
        mainCause:"Sober living for women",
        causes: [
            "women",
            "recovery",
            "drug abuse",
            "substance abuse",
            "addiction",
            "drug addiction",
            "alcoholism",
            "alcohol abuse",
            "sobriety",
            "sober living",
            "sober housing"
        ],
        mission: "The Edna House for Women is dedicated to providing means and opportunity to women affected by alcohol and drug addiction so that they may achieve sobriety by developing mentally, spiritually and emotionally through a blend of 12-step recovery, life, and career services.",
        contactEmail: "mail@ednahouse.org",
        acceptedItems: [
            "Big Books", 
            "cleaning products", 
            "Murphy's Oil Soap", 
            "household cleaner", 
            "cleaner",
            "floor cleaner",
            "bathroom cleaner",
            "cleaning supplies",
            "bleach",
            "sponges",
            "spray bottles",
            "mops",
            "garbage bags",
            "canned food",
            "condiments",
            "snacks",
            "non-perishable snacks",
            "coffee",
            "creamer",
            "sugar",
            "paper towels",
            "toilet paper",
            "tampons",
            "gift cards",
            "bus passes",
            "postage stamps",
            "flash drives",
            "paper",
            "copier paper",
            "printer paper",
            "resume paper",
            "women's clothing",
            "women's shoes",
            "food",
            "toiletries"
        ],
        donationMethod: "Donations may be dropped off at The Edna House seven days a week during daylight hours."
    },
    {
        name: "Dress for Success Cleveland",
        thumbnail: "https://cleveland.dressforsuccess.org/wp-content/uploads/2014/12/DFS_Cleveland-Web.jpg",
        href: "https://cleveland.dressforsuccess.org/",
        address: "2239 East 55th Street",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44103",
        phone: "216-391-2301",
        EIN: "34-1872331",
        mainCause:"Economic independence for women",
        causes: [
            "women",
            "poverty",
            "professional development",
            "economic",
            "economic independence",
            "financial",
            "career",
            "network",
            "networking",
            "support",
            "professional support",
            "work",
            "jobs"
            ],
        mission: "The mission of Dress for Success Cleveland is to promote the economic independence of disadvantaged women by providing professional attire, a network of support and the career development tools to help women thrive in work and life.",
        contactEmail: "DFSC@dressforsuccesscleveland.org",
        acceptedItems: [
            "bus passes",
            "buss pass",
            "gas cards",
            "gift cards",
            "phone cards",
            "grocery gift cards",
            "toiletries",
            "jewelry",
            "women's jewelry",
            "women's coats",
            "women's jackets",
            "coats",
            "jackets",
            "coat",
            "jacket",
            "winter coats",
            "winter coat",
            "winter jacket",
            "winter jackets"
        ],
        donationMethod: "Items may be mailed or dropped off by appointment. Schedule an appointment."
    },
    {
        name: "Domestic Violence & Child Advocacy Center",
        thumbnail: "https://dvcac.org/wp-content/uploads/2017/10/2015-New-Logo-Large-Transparent-2-e1513881586605.png",
        href: "https://dvcac.org/",
        address: "P.O. Box 5466",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44101",
        phone: "216-229-2420",
        EIN: "34-1278377",
        mainCause:"Domestic Violence, Child Abuse",
        causes: [
            "child abuse",
            "human services",
            "domestic violence",
            "shelter",
            "domestic violence shelters",
            "mental health",
            "mental health care",
            "domestic abuse",
            "rape",
            "children",
            "youth",
            "women",
            "girls",
            "child",
            "victim",
            "victims",
            "victims of crime",
            "victims of abuse",
            "abuse",
            "crisis intervention"
        ],
        mission: "Our mission is to provide services that foster safety and healing for those affected by child abuse and domestic violence; and to prevent abuse through education, advocacy, and systemic change.",
        contactEmail: "lreddick @dvcac.org",
        acceptedItems: [
            "gift cards",
            "Target gift cards",
            "Walmart gift cards",
            "Home Depot gift cards",
            "Giant Eagle gift cards",
            "Costco Gift Cards",
            "Visa Gift Cards",
            "body lotion",
            "lotion",
            "deodorant",
            "hand soap dispensers",
            "hand soap",
            "soap",
            "body soap",
            "body wash", 
            "bodywash",
            "towels",
            "wash cloths",
            "paper towels",
            "toilet tissues",
            "tissues", 
            "toilet paper",
            "kleenex",
            "paper products",
            "paper cups", 
            "paper plates",
            "paper bowls",
            "plastic forks" ,
            "plastic spoons",
            "plastic knives",
            "plastic silverware",
            "plastic tableware",
            "disposable forks",
            "disposable spoons",
            "disposable knives",
            "disposable silverware",
            "disposable tableware",
            "dish soap",
            "Clorox cleaning wipes",
            "cleaning wipes",
            "wipes",
            "antibacterial wipes",
            "baby wipes",
            "new crib sheets",
            "size 4 diapers",
            "ethnic hair products",
            "creme of nature shampoo",
            "creme of nature conditioner",
            "creme of nature edge control",
            "shea moisture shampoo",
            "shea moisture conditioner",
            "shea moisture curl enhancing smoothie",
            "pantene shampoo",
            "pantene conditioner",
            "hask shampoo",
            "hask conditioner",
            "ogx shampoo",
            "ogx conditioner",
            "maui moisture shampoo",
            "maui moisture conditioner",
            "perfect results shampoo",
            "perfect results conditioner",
            "perfect results grease",
            "salon pro hair food",
            "salon pro grease",
            "olive oil edge control",
            "olive oil grease",
            "olive oil moisturizer",
            "eco styler gel",
            "wide tooth combs",
            "hard bristle brushes",
            "used cell phones",
            "cell phones"
        ],
        donationMethod: "Call for drop-off times and instructions. Contact Lynette at lreddick @dvcac.org or 216-229-2420."
    },
    {
        name: "Hitchcock Center for Women, Inc.",
        thumbnail: "http://hcfw.org/wp-content/uploads/2017/07/hcfw-logo.png",
        href: "http://hcfw.org/",
        address: "1227 Ansel Rd.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44108",
        phone: "216-421-0662",
        EIN: "34-1264097",
        mainCause:"Residential substance abuse for women and children",
        causes: [
            "women",
            "recovery",
            "addiction",
            "substance abuse",
            "alcohol abuse",
            "drug treatment",
            "alcohol treatment",
            "mental health",
            "mental health treatment",
        ],
        mission: "To wholistically empower women to achieve and maintain productive, chemically free lives at home, work, and in the community.",
        contactEmail: "info@hcfw.org",
        acceptedItems: [
            "nitrile gloves",
            "fleece blanket",
            "travel blanket",
            "blanket",
            "crayons",
            "diapers",
            "similac",
            "baby formula",
            "kids hats",
            "beanies",
            "winter hats",
            "kids winter hats",
            "diaper",
            "kids gloves",
            "winter gloves",
            "winter jackets",
            "kids jackets",
            "winter jacket",
            "kids jacket",
            "girls jacket",
            "boys jacket",
            "winter fleece",
            "fleece",
            "kids fleece",
            "kids winter clothing",
            "puzzle books",
            "crossword puzzles",
            "sudoku",
            "search word",
            "shower caddy",
            "flip flops",
            "shower shoes",
            "pocket planner",
            "planner",
            "planners",
            "crochet hook",
            "crochet hooks",
            "knitting needles",
            "knitting needle",
            "yarn",
            "winter headbands",
            "women's gloves",
            "gloves",
            "winter gloves",
            "winter hats",
            "winter clothing",
            "nail file",
            "nail files",
            "emery boards",
            "emery board",
            "hair brushes",
            "hairbrushes",
            "comb",
            "combs",
            "wig scarves",
            "headbands",
            "bath sponges",
            "mesh pouf",
            "shower pouf",
            "loofah",
            "deodorant",
            "antiperspirant",
            "shampoo",
            "conditioner",
            "silk scrunchies",
            "hair scrunchies",
            "towels",
            "bath towels",
            "towel",
            "bath towel",
            "lotion",
            "hand lotion",
            "body lotion",
            "body wash",
            "shower gel"
            ],
        donationMethod: "Contact info@hcfw.org for information about donation delivery."
    },
    {
        name: "The City Mission",
        thumbnail: "https://www.thecitymission.org/wp-content/uploads/2018/04/logo.png",
        href: "https://www.thecitymission.org/",
        address: "5310 Carnegie Ave.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44103",
        phone: "216-431-3510",
        EIN: "34-0760586",
        mainCause:"Human services",
        causes: [
            "homeless",
            "homeless shelter",
            "homeless shelters",
            "human services",
            "christianity",
            "shelter",
            "trauma",
            "poverty"],
        mission: "To provide help and hope to all people through the transforming power of God's love.",
        contactEmail: "",
        acceptedItems: [
            "walker",
            "baby walker",
            "sports bras",
            "bus ticket",
            "bus tickets",
            "bible",
            "bibles",
            "winter clothing",
            "men's winter clothing",
            "women's winter clothing",
            "children's winter clothing",
            "socks",
            "men's socks",
            "women's socks",
            "children's socks",
            "underwear",
            "men's underwear",
            "women's underwear",
            "children's underwear",
            "t-shirts",
            "men's t-shirts",
            "women's t-shirts",
            "children's t-shirts",
            "pillows",
            "twin sheets",
            "twin blankets",
            "shower curtains",
            "towels",
            "wash cloths",
            "bath towels",
            "hand towels",
            "ibuprofen",
            "advil",
            "tylenol",
            "acetaminophen",
            "cold medicine",
            "cold medication",
            "cough drops",
            "cough medicine",
            "cough medication",
            "kids movies",
            "kids DVDs",
            "craft supplies",
            "tissue paper",
            "construction paper",
            "poster paints",
            "glitter paint",
            "googley eyes",
            "markers",
            "diapers",
            "wipes",
            "baby wipes",
            "strollers",
            "stroller",
            "double stroller",
            "double strollers",
            "double-stroller",
            "play pen",
            "pack n' play",
            "bassinette",
            "shampoo",
            "conditioner",
            "body wash",
            "soap",
            "deodorant",
            "toothpaste",
            "toothbrush",
            "feminine hygiene products",
            "tampons",
            "baby wash",
            "baby soap",
            "vaseline",
            "ethnic hair",
            "ethnic hair products",
            "bath and body works",
            "jewelry",
            "costume jewelry",
            "gift cards",
            "calendars",
            "planners",
            "pocket calendars",
            "journals",
            "devotionals",
            "razors",
            "saving cream",
            "comb",
            "combs",
            "razor",
            "after shave",
            "aftershave",
            "cologne",
            "backpacks",
            "backpack",
            "duffel bags",
            "duffel bag",
            "shower shoes",
            "flip flops",
            "dress shirt",
            "dress shirts",
            "shirts",
            "polo shirts",
            "polo shirt",
            "wallet",
            "wallets",
            "sports gear",
            "Cleveland sports gear",
            "school supplies",
            "baby formula",
            "diapers",
            "toiletries",
            "clothing",
            "furniture",
            "couch",
            "couches",
            "bed frames",
            "coffee tables",
            "bedding",
            "dresser",
            "dressers",
            "oven",
            "stove",
            "refrigerator",
            "microwave",
            "coffee maker",
            "kitchen utensils",
            "pots",
            "pans",
            "dishes",
            "electronics",
            "tv",
            "dvd players",
            "outdoor equipment",
            "shovel",
            "snow shovel",
            "lawnmower",
            "maintenance supplies",
            "appliances",
            ],
        donationMethod: "Donations are currently accepted Monday through Friday from 10:00 a.m. to 4:00 p.m. at 5310 Carnegie Avenue, Cleveland."
    },
    {
        name: "L'Arche Cleveland",
        thumbnail: "https://www.larchecleveland.org/wp-content/uploads/2020/06/LArche-Cleveland-Online.png",
        href: "https://www.larchecleveland.org/",
        address: "11811 Shaker Blvd. Ste 116",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44120",
        phone: "216-721-2614",
        EIN: "34-1193618",
        mainCause:"Group homes for the disabled",
        causes: [
            "shelter care",
            "residential care",
            "shelter",
            "group home",
            "disabilities",
            "disabled",
            "disabled adults",
            "intellectual disabilities"],
        mission: "L'Arche Cleveland, Inc is a not for profit, faith-based community agency which provides homes and services to adults with intellectual and developmental disabilities.",
        contactEmail: "office@larchecleveland.org",
        acceptedItems: [
            "masks",
            "disposable masks",
            "reusable masks",
            "hand sanitizer",
            "bleach",
            "disinfectant",
            "wipes",
            "antibacterial wipes",
            "gift cards",
            "twin bedding",
            "bedding",
            "towels",
            "bath towels",
            "hand towels",
            "kitchen towels",
            "towels",
            "throw blankets",
            "blanket",
            "blankets",
            "rice cooker",
            "slow cooker",
            "rice steamer",
            "crock pot",
            "sitting chair",
            "chair",
            "chairs"
        ],
        donationMethod: "L'Arche will arrange pick-up or porch drop-off at one of our locations. Please contact Alex at alex@larchecleveland.org or 216-721-2614 to schedule pick-up."
    },
    {
        name: "Talespinner Children's Theatre",
        thumbnail: "https://www.talespinnerchildrenstheatre.org/images/tct-logo.png",
        href: "https://www.talespinnerchildrenstheatre.org/",
        address: "5209 Detroit Avenue",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44102",
        phone: "216-264-9680",
        EIN: "45-3334641",
        mainCause:"Arts and Culture for children",
        
        causes: [
            "arts",
            "cuture",
            "arts and culture",
            "theater",
            "performing arts",
            "performing arts education",
            "education",
            "special needs education",
            "multicultural education",
            "children",
            "youth",
            "families",
            "immigrants",
            "migrants",
            "poverty",
            "economically disadvantaged people"],
        mission: "Talespinner Children's Theatre develops and produces highly imaginative, original, collaborative and interactive professional works for children that also stimulate creative growth in its artists. These pieces involve acting, dance, music, puppetry, and numerous other artistic disciplines, and are open to all creative possibility. TCT creates work that remembers that children are smaller people, not lesser people. Talespinner Children's Theater strives to reach across socio-economic, cultural and traditional boundaries to help awaken and bring better understanding by opening eyes, ears, hearts and imaginations in the young people (and artists) of Cleveland and its surrounds.",
        contactEmail: "info@talespinnerchildrenstheater.org",
        acceptedItems: [
            "book shelves",
            "utility shelves",
            "storage bins",
            "rolling carts",
            "tool cabinet",
            "yoga mats",
            "floor mats",
            "runners",
            "vaccuum",
            "vaccuum cleaner",
            "shop vac",
            "extension cord",
            "extension cords",
            "power strip",
            "power strips",
            "gift cards"],
        donationMethod: "Contact us for pick-up of local donations. Items may also be delivered directly to the theater at 5209 Detroit Avenue, Cleveland."
    },
    {
        name: "Neiborhood Pets Outreach & Resource Center",
        thumbnail: "http://www.neighborhoodpetscle.org/uploads/7/7/9/8/77980490/nhood-pets-logo-color.jpg",
        href: "http://www.neighborhoodpetscle.org/",
        address: "3711 East 65th St.",
        city: "Cleveland",
        state: "Ohio",
        zipCode: "44105",
        phone: "216-505-5853",
        EIN: "27-2026307",
        mainCause:"Animal Welfare",
        causes: [
            "animals",
            "pets",
            "domesticated animals",
            "animal welfare",
            "human services"],
        mission: "Neibhorhood Pets recognizes the many benefits of the human animal bond, and supports people with financial needs by helping them keep their pets in their homes. We do this by providing access to affordable pet care, resources, information and other supportive services. Our welcoming environment is designed to foster trust and create long-lasting relationships as we build community.",
        contactEmail: "info@neighborhoodpetscle.org",
        acceptedItems: [
            "dry cat food",
            "cat food",
            "canned cat food",
            "cat treats",
            "scratching pads",
            "scratching posts",
            "cat litter",
            "clumping cat litter",
            "cat collars",
            "breakaway cat collars",
            "cat carriers",
            "cat beds",
            "feliway spray",
            "dog food",
            "dry dog food",
            "dog treats",
            "kongs",
            "nylabones",
            "slow-feed bowls",
            "jolly balls",
            "durable soft toys",
            "dog beds",
            "pet beds",
            "martingale collars",
            "dog leashes",
            "freedom harness",
            "easy walk harness",
            "creamy peanut butter",
            "spray cheese",
            "gift cards",
            "bleach",
            "paper towels",
            "towels",
            "all-purpose cleaner",
            "copy paper",
            "printer paper",
            "envelopes",
            "stamps",
            "storage tubs",
            "freezer bags",
            "address labels",
            "shipping labels",
            "bottled water", 
            "pop-up tents",
            "folding table",
            "folding tables",
            "folding chair",
            "folding chairs",
            "id tag engraving machine",
            "laptops",
            "laptop",
            "iPad",
            "iPads",
            "otoscope",
            "microscope"
            ],
        donationMethod: "Donations may be dropped off at our Slavic Village location (3711 E 65th St. Cleveland, OH) on Tuesdays & Thursdays between noon and 4:00 p.m., and Saturdays between 10:00 a.m. and 2:00 p.m. Contact us at info@neighborhoodpetscle.org or 216-505-5853 to schedule drop-off during other times."
    },

    
    
]
db.Charity.remove({})
  .then(() => db.Charity.collection.insertMany(charitySeed))
  .then(data => {
    console.log(data.result.n + " records inserted!");
    process.exit(0);
  })
  .catch(err => {
    console.error(err);
    process.exit(1);
  });

//   {
//     name: "",
//     thumbnail: "",
//     href: "",
//     address: "",
//     city: "",
//     state: "",
//     zipCode: "",
//     phone: "",
//     EIN: "",
//     mainCause:"",
//     causes: [""],
//     mission: "",
//     contactEmail: "",
//     acceptedItems: [""],
//     donationMethod: ""
// }