const mongoose = require("mongoose");
const db = require("../models");

//need file to empty the Charity collection and insert charities below??

mongoose.connect(
    process.env.MONGODB_URI || "mongodb://localhost/reactrecipes"
  );

const charitySeed = [
    {
        name: "Edna House",
        thumbnail: "",
        href: "www.ednahouse.org",
        address: "2007 West 65th Street",
        city: "Cleveland",
        zipCode: 44102,
        phone: "216-281-7751",
        EIN: "14-1912872",
        causes: [
            "women",
            "recovery",
            "drug abuse",
            "substance abuse",
            "addiction",
            "drug addiction",
            "alcoholism",
            "alcohol abuse",
            "sobriety",
            "sober living",
            "sober housing"
        ],
        mission: "The Edna House for Women is dedicated to providing means and opportunity to women affected by alcohol and drug addiction so that they may achieve sobriety by developing mentally, spiritually and emotionally through a blend of 12-step recovery, life, and career services.",
        contactEmail: "mail@ednahouse.org",
        acceptedItems: [
            "Big Books", 
            "cleaning products", 
            "Murphy's Oil Soap", 
            "household cleaner", 
            "cleaner",
            "floor cleaner",
            "bathroom cleaner",
            "cleaning supplies",
            "bleach",
            "sponges",
            "spray bottles",
            "mops",
            "garbage bags",
            "canned food",
            "condiments",
            "snacks",
            "non-perishable snacks",
            "coffee",
            "creamer",
            "sugar",
            "paper towels",
            "toilet paper",
            "tampons",
            "gift cards",
            "bus passes",
            "postage stamps",
            "flash drives",
            "paper",
            "copier paper",
            "printer paper",
            "resume paper",
            "women's clothing",
            "women's shoes",
            "food",
            "toiletries"
        ],
        donationMethod: "Donations may be dropped off at The Edna House seven days a week during daylight hours."
    },
    {
        name: "Dress for Success Cleveland",
        thumbnail: "https://cleveland.dressforsuccess.org/wp-content/uploads/2014/12/DFS_Cleveland-Web.jpg",
        href: "https://cleveland.dressforsuccess.org/",
        address: "2239 East 55th Street",
        city: "Cleveland",
        zipCode: "44103",
        phone: "216-391-2301",
        EIN: "34-1872331",
        causes: [
            "women",
            "poverty",
            "professional development",
            "economic",
            "economic independence",
            "financial",
            "career",
            "network",
            "networking",
            "support",
            "professional support",
            "work",
            "jobs"
            ],
        mission: "The mission of Dress for Success Cleveland is to promote the economic independence of disadvantaged women by providing professional attire, a network of support and the career development tools to help women thrive in work and life.",
        contactEmail: "DFSC@dressforsuccesscleveland.org",
        acceptedItems: [
            "bus passes",
            "buss pass",
            "gas cards",
            "gift cards",
            "phone cards",
            "grocery gift cards",
            "toiletries",
            "jewelry",
            "women's jewelry",
            "women's coats",
            "women's jackets",
            "coats",
            "jackets",
            "coat",
            "jacket",
            "winter coats",
            "winter coat",
            "winter jacket",
            "winter jackets"
        ],
        donationMethod: "Items may be mailed or dropped off by appointment. Schedule an appointment."
    },
    {
        name: "Domestic Violence & Child Advocacy Center",
        thumbnail: "http://test.dvcac.org/wp/",
        href: "https://dvcac.org/",
        address: "P.O. Box 5466",
        city: "Cleveland",
        zipCode: "44101",
        phone: "216-229-2420",
        EIN: "34-1278377",
        causes: [
            "child abuse",
            "human services",
            "domestic violence",
            "shelter",
            "domestic violence shelters",
            "mental health",
            "mental health care",
            "domestic abuse",
            "rape",
            "children",
            "youth",
            "women",
            "girls",
            "child",
            "victim",
            "victims",
            "victims of crime",
            "victims of abuse",
            "abuse",
            "crisis intervention"
        ],
        mission: "Our mission is to provide services that foster safety and healing for those affected by child abuse and domestic violence; and to prevent abuse through education, advocacy, and systemic change.",
        contactEmail: "lreddick @dvcac.org",
        acceptedItems: [
            "gift cards",
            "Target gift cards",
            "Walmart gift cards",
            "Home Depot gift cards",
            "Giant Eagle gift cards",
            "Costco Gift Cards",
            "Visa Gift Cards",
            "body lotion",
            "lotion",
            "deodorant",
            "hand soap dispensers",
            "hand soap",
            "soap",
            "body soap",
            "body wash", 
            "bodywash",
            "towels",
            "wash cloths",
            "paper towels",
            "toilet tissues",
            "tissues", 
            "toilet paper",
            "kleenex",
            "paper products",
            "paper cups", 
            "paper plates",
            "paper bowls",
            "plastic forks" ,
            "plastic spoons",
            "plastic knives",
            "plastic silverware",
            "plastic tableware",
            "disposable forks",
            "disposable spoons",
            "disposable knives",
            "disposable silverware",
            "disposable tableware",
            "dish soap",
            "Clorox cleaning wipes",
            "cleaning wipes",
            "wipes",
            "antibacterial wipes",
            "baby wipes",
            "new crib sheets",
            "size 4 diapers",
            "ethnic hair products",
            "creme of nature shampoo",
            "creme of nature conditioner",
            "creme of nature edge control",
            "shea moisture shampoo",
            "shea moisture conditioner",
            "shea moisture curl enhancing smoothie",
            "pantene shampoo",
            "pantene conditioner",
            "hask shampoo",
            "hask conditioner",
            "ogx shampoo",
            "ogx conditioner",
            "maui moisture shampoo",
            "maui moisture conditioner",
            "perfect results shampoo",
            "perfect results conditioner",
            "perfect results grease",
            "salon pro hair food",
            "salon pro grease",
            "olive oil edge control",
            "olive oil grease",
            "olive oil moisturizer",
            "eco styler gel",
            "wide tooth combs",
            "hard bristle brushes",
            "used cell phones",
            "cell phones"
        ],
        donationMethod: "Call for drop-off times and instructions. Contact Lynette at lreddick @dvcac.org or 216-229-2420."
    },
    {
        name: "",
        thumbnail: "",
        href: "",
        address: "",
        city: "",
        zipCode: "",
        phone: "",
        EIN: "",
        causes: [""],
        mission: "",
        contactEmail: "",
        acceptedItems: [""],
        donationMethod: ""
    },
]